services:
  web:
    image: ghcr.io/cleaver/sb_cascade/sb_exe2e:latest
    ports:
      - "4000:4000"
    # For test only
    environment:
      - PHX_HOST=localhost
      - DATABASE_URL=ecto://postgres:password@db/sb_cascade_prod
      - SECRET_KEY_BASE=kCSLcoa2Nu7HnvoQXV8RwoTtEy7oT2wfSwdfcryduc8PNUwj3Iz2MrJBVC4fBdx5
      - HOST=0.0.0.0
    depends_on:
      - db
    networks:
      - default

  db:
    image: ghcr.io/cleaver/sb_cascade/sb_dbe2e:latest
    # For test only
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sb_cascade_prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    name: sb_cascade_prod
