name: Build Docker Image

# Trigger the workflow on pushes or merges to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker to be used in the GitHub Actions environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional if you need to push to a registry)
      # You need to set DOCKER_USERNAME and DOCKER_PASSWORD secrets in your repository
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/sb_exe2e:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/sb_exe2e:latest
