name: Build Docker Image

# Trigger the workflow on pushes or merges to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker to be used in the GitHub Actions environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional if you need to push to a registry)
      # You need to set DOCKER_USERNAME and DOCKER_PASSWORD secrets in your repository
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t sb_exe2e:latest .

      # Optionally push the Docker image to a registry (like Docker Hub)
      - name: Push the Docker image
        run: |
          docker tag sb_exe2e:latest ghcr.io/cleaver/sb_exe2e:latest
          docker push ghcr.io/cleaver/sb_exe2e:latest
