name: Build Elixir Latest Image

# Trigger the workflow on pushes or merges to the `main` branch after tests pass
on:
  workflow_run:
    workflows: ["Elixir CI"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker to be used in the GitHub Actions environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/sb_prod:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/sb_prod:latest
