name: GHCR Cleanup

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  ghcr_cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          older-than: 60 days
          keep-n-tagged: 5
          dry-run: false
